version: "3.8"

services:
  deepseek-coder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepseek-coder
    ports:
      - "8080:80"
      - "5900:5900"
      - "7860:7860"
    volumes:
      - ./app:/app
    environment:
      - VNC_PASSWORD=myvncpassword # Установи пароль для VNC, если нужно
    restart: unless-stopped
